global:
  scrape_interval: 30s
scrape_configs:
  - job_name: mc-vanilla-monitor
    static_configs:
      - targets:
          - mc-vanilla-monitor:8080
  - job_name: moneyforward
    scrape_interval: 1m
    static_configs:
      - targets:
          - mf-exporter:8000
